name: "Pull Request Labeler"
on:
- pull_request

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/labeler@v5
    with:
      configuration-path: .github/labels.yml
      sync-labels: true